### ISSUE TITLE
Search bar not working, keeps crashing

### ISSUE THREAD

**Issue by vibestepler** [vvbbnn00/onedrive-index#14]
![image](https://github.com/vvbbnn00/onedrive-index/assets/144337960/e2b87e9b-a77b-4553-9a93-77058b98f866)

**Comment by vibestepler** [comment]
framework-de9232d192263565.js:9 TypeError: Cannot read properties of undefined (reading 'slice')
    at getRawExtension (5349-bd8d89f4684b8374.js:1:70789)
    at getExtension (5349-bd8d89f4684b8374.js:1:70857)
    at getFileIcon (5349-bd8d89f4684b8374.js:1:70922)
    at SearchResultItemTemplate (5349-bd8d89f4684b8374.js:1:52390)
    at Xh (framework-de9232d192263565.js:9:60992)
    at x (framework-de9232d192263565.js:9:119447)
    at Vk (framework-de9232d192263565.js:9:99132)
    at framework-de9232d192263565.js:9:98999
    at Jk (framework-de9232d192263565.js:9:99006)
    at Ok (framework-de9232d192263565.js:9:95762)
Mi @ framework-de9232d192263565.js:9
main-cf6e1d8c39f3c97e.js:1 TypeError: Cannot read properties of undefined (reading 'slice')
    at getRawExtension (5349-bd8d89f4684b8374.js:1:70789)
    at getExtension (5349-bd8d89f4684b8374.js:1:70857)
    at getFileIcon (5349-bd8d89f4684b8374.js:1:70922)
    at SearchResultItemTemplate (5349-bd8d89f4684b8374.js:1:52390)
    at Xh (framework-de9232d192263565.js:9:60992)
    at x (framework-de9232d192263565.js:9:119447)
    at Vk (framework-de9232d192263565.js:9:99132)
    at framework-de9232d192263565.js:9:98999
    at Jk (framework-de9232d192263565.js:9:99006)
    at Ok (framework-de9232d192263565.js:9:95762)
renderError @ main-cf6e1d8c39f3c97e.js:1
main-cf6e1d8c39f3c97e.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
renderError @ main-cf6e1d8c39f3c97e.js:1
framework-de9232d192263565.js:9 TypeError: Cannot read properties of undefined (reading 'slice')
    at getRawExtension (5349-bd8d89f4684b8374.js:1:70789)
    at getExtension (5349-bd8d89f4684b8374.js:1:70857)
    at getFileIcon (5349-bd8d89f4684b8374.js:1:70922)
    at SearchResultItemTemplate (5349-bd8d89f4684b8374.js:1:52390)
    at Xh (framework-de9232d192263565.js:9:60992)
    at x (framework-de9232d192263565.js:9:119447)
    at Vk (framework-de9232d192263565.js:9:99132)
    at framework-de9232d192263565.js:9:98999
    at Jk (framework-de9232d192263565.js:9:99006)
    at Ok (framework-de9232d192263565.js:9:95762)
Mi @ framework-de9232d192263565.js:9
main-cf6e1d8c39f3c97e.js:1 TypeError: Cannot read properties of undefined (reading 'slice')
    at getRawExtension (5349-bd8d89f4684b8374.js:1:70789)
    at getExtension (5349-bd8d89f4684b8374.js:1:70857)
    at getFileIcon (5349-bd8d89f4684b8374.js:1:70922)
    at SearchResultItemTemplate (5349-bd8d89f4684b8374.js:1:52390)
    at Xh (framework-de9232d192263565.js:9:60992)
    at x (framework-de9232d192263565.js:9:119447)
    at Vk (framework-de9232d192263565.js:9:99132)
    at framework-de9232d192263565.js:9:98999
    at Jk (framework-de9232d192263565.js:9:99006)
    at Ok (framework-de9232d192263565.js:9:95762)
renderError @ main-cf6e1d8c39f3c97e.js:1
main-cf6e1d8c39f3c97e.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
renderError @ main-cf6e1d8c39f3c97e.js:1
main-cf6e1d8c39f3c97e.js:1 Error rendering page:  Error: Cancel rendering route
    at _ (main-cf6e1d8c39f3c97e.js:1:13997)
    at main-cf6e1d8c39f3c97e.js:1:13949
    at new Promise (<anonymous>)
    at doRender (main-cf6e1d8c39f3c97e.js:1:13926)
    at main-cf6e1d8c39f3c97e.js:1:12063
(anonymous) @ main-cf6e1d8c39f3c97e.js:1

**Comment by vvbbnn00** [comment]
Hello, it looks like the issue is caused by passing `driveItem?.name` as `undefined` when calling the `getFileIcon` function in the code block below. To simply avoid this problem, you just need to add an extra check for whether `fileName` is `undefined` when calling the `getRawExtension` function.

https://github.com/vvbbnn00/onedrive-index/blob/86c689f5b66a4bc3fe9562dc149cfeeb6c27c383/app/src/components/SearchModal.tsx#L100


https://github.com/vvbbnn00/onedrive-index/blob/86c689f5b66a4bc3fe9562dc149cfeeb6c27c383/app/src/utils/getFileIcon.ts#L112-L132

However, to further understand the root cause of the issue, could you provide the specific search result file that caused the error? The specific steps can be as follows:

![image](https://github.com/vvbbnn00/onedrive-index/assets/46409975/7e03a322-1d48-4fab-9302-b301a889f52f)

As shown in the figure, after you perform a search, you should be able to capture multiple requests. The first request returns the files that meet the criteria, along with their encrypted IDs. The subsequent requests are to retrieve the file details based on the encrypted IDs of the files. At this point, if possible, could you compare the responses and find the part where there is an abnormal response? For example, the response might be missing the `name` field, etc. (You don't need to provide the 401 error response, as this is probably not an error, but just a lack of permission to access the file because you are not logged in.)

Thank you for your assistance.

**Comment by vibestepler** [comment]
Site = https://onedrive-index.fly.dev/

Permissions = Files.Read.All , offline_access , User.Read

**Comment by vibestepler** [comment]
![image](https://github.com/vvbbnn00/onedrive-index/assets/144337960/151377ca-53ad-4cf5-bfd4-05608ad0f22b)


![image](https://github.com/vvbbnn00/onedrive-index/assets/144337960/3e0ffd3f-a755-4727-8dcd-88de684146c1)

**Comment by vvbbnn00** [comment]
It looks like you might be using OneDrive Personal. Since I don't have a readily available account on hand, it might take some time to confirm. I will get back to you later.

**Comment by vibestepler** [comment]
Yes its OneDrive Personal Account.

**Comment by vvbbnn00** [comment]
After analysis, I found that there seems to be a difference in file ID generation between the personal version of OneDrive and the business version. In the business version, the file ID appears to be a string composed of uppercase letters and numbers, while in the personal version, it also includes the ! symbol, for example: `ABCDEF1234567890!114`. In the validation of the `/api/item` interface, only IDs containing letters and numbers are allowed to pass, which is what caused the problem.

**Comment by vvbbnn00** [comment]
I've initiated a pull request, maybe this will help you.

**Comment by vibestepler** [comment]
thanks
